### ISSUE TITLE
tutorial para gerar este app

### ISSUE THREAD

**Issue by ricardodarocha** [ErickPetru/kinghost2020-universal-apps#1]

**Comment by ricardodarocha** [comment]
Caso possa nos compartilhar o tutorial da linha de comandos, passo a passo, seria de grande utilidade para os estudantes.
Grato

**Comment by ErickPetru** [comment]
Olá @ricardodarocha, tudo bem? O [README](https://github.com/ErickPetru/kinghost2020-universal-apps#readme) aqui do repositório já fala do que precisa para rodar este projeto. Claro, considerando um ambiente com Node.js já instalado e funcionando, o que é pré-requisito para qualquer coisa relacionada a desenvolvimento _front-end_ moderno com _frameworks_.

Agora, se a dúvida é como criar um novo projeto do zero com Nuxt, é só seguir o [início do guia deste _framework_](https://nuxtjs.org/docs/2.x/get-started/installation). Bons estudos!
